title: Augusto Mérida García
logo: assets/images/1740711276660.png
description: Bienvenido a mi portafolio donde conoceras más sobre mí y mis proyectos como Analista de Datos.
#show_downloads: true
theme: jekyll-theme-minimal
